<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraduationProject.Abstraction\GraduationProject.Services.Abstraction.csproj" />
    <ProjectReference Include="..\GraduationProject.Services\GraduationProject.Services.csproj" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />


	</ItemGroup>
</Project>
